### ISSUE TITLE
PyPI

### ISSUE THREAD

**Issue by jayvdb** [tonybenoy/paur#1]
Could you do a PyPI release, if only to reserve the name.

**Comment by tonybenoy** [comment]
Hi @jayvdb thanks for the interest in the project. It's still no where I planned to bring it up to speed. I'll package  it and update it on pypi but I still need to do more with this.

**Comment by jayvdb** [comment]
You can mark the PyPI release as a pre-release if you like, but it is full of alpha quality work which isnt marked as pre-release ;-)

**Comment by tonybenoy** [comment]
Sure I'll do that.

**Comment by tonybenoy** [comment]
@jayvdb  So it took me 10 months to get to finally do this sadly due to a lack of time :sweat_smile: . Sorry about that.
I've spilt this into 2 https://github.com/tonybenoy/aurlib and https://github.com/tonybenoy/aorlib for user repository and official repository and also available on pypi. I split them out so I could work on paur as an aur helper independently of this. Closing this issue. Will probably keep updating all 3(I hope hope I don't fall back again) !

**Comment by jayvdb** [comment]
Awesome.  I have created https://build.opensuse.org/package/show/home:jayvdb:py-new/python-aurlib and https://build.opensuse.org/package/show/home:jayvdb:py-new/python-aorlib .  Next step, tests :P

**Comment by tonybenoy** [comment]
@jayvdb  thanks. Hopefully I'll do that more quickly than last time😅
